apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: loadbalancer
spec:
  ports:
  - name: 8080-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-webapp
  type: LoadBalancer
status:
  loadBalancer: {}
