apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: loadbalancer
  name: loadbalancer
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: loadbalancer
  type: NodePort
status:
  loadBalancer: {}
